### ISSUE TITLE
example suggestion: basic Dict usage in roc

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/examples#101]

**Comment by frisoft** [comment]
I would like to contribute to this issue. My PR is here: https://github.com/roc-lang/examples/pull/128

I know I should have first asked in the chat, but i wasn't sure about the result of my code.

**Comment by frisoft** [comment]
I've just noticed the CI script. I'll add tests for it. Keeping the PR as a Draft, for now.

**Comment by frisoft** [comment]
The PR is ready to review. Please.

**Comment by Anton-4** [comment]
Thanks @frisoft! I'll try to review today :)

**Comment by Anton-4** [comment]
I've made some changes, but it's late for me so I'm going to test and review the final code tomorrow.
