### ISSUE TITLE
example suggestion: Multi-line comments

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/examples#122]
There is no multi-line comment syntax in Roc, you'll need to use `#` before every line. This is necessary to allow roc programs to be used as bash scripts. Most editors allow you to comment several lines at once using a shortcut like Ctrl+/ on vscode.

It's a bit strange to have an example that basically says "there is no multi-line comment syntax" but I think it's useful when searching for answers.

**Comment by dotslashbit** [comment]
I have created a PR for this, please check and let me know if there's any modification needed
