### ISSUE TITLE
example suggestion: minimal two file project

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/examples#127]
[inspiration](https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/.E2.9C.94.20Most.20basic.20way.20to.20split.20code.20across.20files/near/407935137)

**Comment by frisoft** [comment]
Can I work on this one, @Anton-4?
How should it be titled? "Use of an Interface module" or something?

**Comment by lukewilliamboswell** [comment]
I'd say go for it 👍 re the name, I think Interface Modules is ok to start with. I imagine as you go you may find a better name.

**Comment by frisoft** [comment]
Thank you, @lukewilliamboswell.
Starting from https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/.E2.9C.94.20Most.20basic.20way.20to.20split.20code.20across.20files/near/407935137

I was thinking it would be good to have 2 modules in the example to show the following:
- You can have 2 functions with the same name in 2 different Interface modules (i.e. AddOne and AddOneStr).
- You can expose only some of the functions, keeping the others private.

Hope this doesn't make it too complex.

WDYT?

**Comment by Anton-4** [comment]
I'd really like to have a minimal complexity example with one app module and one interface module. Perhaps the interface module can just expose something like:
```
hello : Str
hello = "Hello from interface!"
```

After we have the minimal example, we could do another one that uses e.g. multiple interfaces grouped in a folder, some exposed and some private functions, a simple opaque type...

**Comment by frisoft** [comment]
It makes sense. Thank you, @Anton-4. I'll create a PR for it.

**Comment by frisoft** [comment]
The PR is ready: https://github.com/roc-lang/examples/pull/133
Could you please review it?
