### ISSUE TITLE
check all examples with `roc format` in the github ci workflow

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/examples#131]

**Comment by frisoft** [comment]
I guess that you mean trying to format every example and fail if the test if the output of `roc format` is not the same as the source code. Am I right?

This skipping examples/Tasks/main.roc for now, as `roc format` does not work with it.

It depends on https://github.com/roc-lang/examples/pull/132

Please assign it to me.

**Comment by frisoft** [comment]
Here is the PR for this issue: https://github.com/roc-lang/examples/pull/134
It is failing for now (Draft), but when the one with all the formatting is merged, it can be reviewed and merged.
