### ISSUE TITLE
ld: warning when running example

### ISSUE THREAD

**Issue by lukewilliamboswell** [roc-lang/examples#35]
```
% roc test examples/PatternMatching/PatternMatching.roc 
ld: warning: -undefined dynamic_lookup may not work with chained fixups

0 failed and 7 passed in 572 ms.
```

**Comment by lukewilliamboswell** [comment]
When I run this in the shell, after `nix develop` I don't see any issues. I guess that means this was just a local issue with my configuration and we can close this @Anton-4 ?

**Comment by Anton-4** [comment]
Yes, I think this was happening because you were using an older version of roc.
