### ISSUE TITLE
Example suggestion: tuples in roc

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/examples#50]
Tuples are not mentioned in the tutorial so it would be nice to have a basic example demonstrating how they are commonly used.

**Comment by lukewilliamboswell** [comment]
We do have an issue to add Tuple to the tutorial [#5141](https://github.com/roc-lang/roc/issues/5141), I think @kunalznk is working on that, but I haven't checked in on that for a while.

**Comment by Anton-4** [comment]
Even if it's mentioned in the tutorial, I think it would be useful to have an example that demonstrates how they work, their type signature, pattern matching with tuples...
