### ISSUE TITLE
update to new roc-json release when it is available

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/examples#98]
There are currently issues because the latest roc nightly has changed the api for drop, dropList, and dropLast.
I've already made a PR for roc-json: https://github.com/lukewilliamboswell/roc-json/pull/4

**Comment by lukewilliamboswell** [comment]
New release is available https://github.com/lukewilliamboswell/roc-json/releases/tag/v0.4.0

**Comment by Anton-4** [comment]
Nice, thanks @lukewilliamboswell :heart:
